### ISSUE TITLE
English gone wrong

### ISSUE THREAD

**Issue by Piuuf** [PaulCombal/ExoLife#1]
color_under is not a valid variable name. Under is in a physical scheme. Below is a better word for this particular use case.
u patetic piec of shiet

**Comment by GhislainGloria** [comment]
Fermes la @Piuuf  tu auras le droit de parler quand tu auras un esprit

**Comment by Piuuf** [comment]
support : 10/10 would ask again

**Comment by GhislainGloria** [comment]
@Piuuf T'es pas tout seul dans ta tête !
